Final Code
Bank Management System Final Code

diff --git a/Project/accounts/custview b/Project/accounts/custview
--- a/Project/accounts/custview
+++ b/Project/accounts/custview
@@ -1,31 +1,70 @@
 #! /bin/bash
-clear
+
 let " mon= 100000000000000 + $1"
-echo -e "\n\tDetails\n"
+if [ -f "$1" ] ;
+then
+	clear
+	echo -e "\n\n"
+	echo -e "\t                                    _     _____       _        _ _     "
+	echo -e "\t     /\                            | |   |  __ \     | |      (_) |    "
+	echo -e "\t    /  \   ___ ___ ___  _   _ _ __ | |_  | |  | | ___| |_ __ _ _| |___ "
+	echo -e "\t   / /\ \ / __/ __/ _ \| | | |  _  | __| | |  | |/ _ \ __/ _  | | / __|"
+	echo -e "\t  / ____ \ (_| (_| (_) | |_| | | | | |_  | |__| |  __/ || (_| | | \__ \ "
+	echo -e "\t /_/    \_\___\___\___/ \__,_|_| |_|\__| |_____/ \___|\__\__,_|_|_|___/"
 
-echo -en "\n\nAccount No : "
-echo $(head -1 $1 | tail +1)
+	echo -en "\n\nAccount No : "
+	echo $(head -1 $1 | tail +1)
 
-echo -en "Name : "
-echo $(head -4 $1 | tail +4)
+	echo -en "Name : "
+	echo $(head -4 $1 | tail +4)
 
-echo -en "Address : "
-echo $(head -5 $1 | tail +5)
+	echo -en "Address : "
+	echo $(head -5 $1 | tail +5)
 
-echo -en "Date of Birth (dd/mm/yyyy) : "
-echo $(head -6 $1 | tail +6)
+	echo -en "Date of Birth (dd/mm/yyyy) : "
+	echo $(head -6 $1 | tail +6)
 
-echo -en "Aadhar No : "
-echo $(head -7 $1 | tail +7)
+	echo -en "Aadhar No : "
+	echo $(head -7 $1 | tail +7)
 
-echo -en "Email : "
-echo $(head -8 $1 | tail +8)
+	echo -en "Email : "
+	echo $(head -8 $1 | tail +8)
 
-echo -en "Mobile No : "
-echo $(head -9 $1 | tail +9)
+	echo -en "Mobile No : "
+	echo $(head -9 $1 | tail +9)
 
-echo -en "Bal : "
-echo $(head -1 ./balance/$mon | tail +1 )
-echo -e "\n\nPress Any Key To Continue "
-read ge
+	echo -en "Bal : "
+	echo $(head -1 ./balance/$mon | tail +1 )
+	echo -e "\n\nPress Any Key To Continue "
+	read ge
+
+else
+
+	echo -e "\n\nAccount not Found !!!" 
+	echo -e "Press Any Key To Continue "
+	read ge
+fi
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
diff --git a/Project/adedit b/Project/adedit
--- a/Project/adedit
+++ b/Project/adedit
@@ -1,93 +1,166 @@
 #! /bin/bash
 
 clear
-echo -en "\n\n\tEdit Details\n\nEnter Your Account No : "
+
+echo -en "\n\t  ______    _ _ _     _____       _        _ _      "
+echo -en "\n\t |  ____|  | (_) |   |  __ \     | |      (_) |     "
+echo -en "\n\t | |__   __| |_| |_  | |  | | ___| |_ __ _ _| |___  "
+echo -en "\n\t |  __| / _  | | __| | |  | |/ _ \ __/ _  | | / __| "
+echo -en "\n\t | |___| (_| | | |_  | |__| |  __/ || (_| | | \__ \ "
+echo -en "\n\t |______\____|_|\__| |_____/ \___|\__\____|_|_|___/ "
+
+echo -en "\n\n\nEnter Your Account No : "
 read acc
 cd ./accounts
+
 if [ -f "$acc" ];
 then
-echo -en "\n1. Password \n2. Address \n3. DOB \n4. Aadhar \n5. Email \n6. Phone No \n7. Exit \n Enter Your Choice "  
-read cq
-case $cq in
+l=1
+while [ $l -eq 1 ]
+do
+	clear
+	
+	echo -en "\n\t  ______    _ _ _     _____       _        _ _      "
+	echo -en "\n\t |  ____|  | (_) |   |  __ \     | |      (_) |     "
+	echo -en "\n\t | |__   __| |_| |_  | |  | | ___| |_ __ _ _| |___  "
+	echo -en "\n\t |  __| / _  | | __| | |  | |/ _ \ __/ _  | | / __| "
+	echo -en "\n\t | |___| (_| | | |_  | |__| |  __/ || (_| | | \__ \ "
+	echo -en "\n\t |______\____|_|\__| |_____/ \___|\__\____|_|_|___/ "
+	echo -en "\n\n1. Password \n2. Address \n3. DOB \n4. Aadhar \n5. Email \n6. Phone No \n7. Exit \n\nEnter Your Choice : "  
+	read cq
+		case $cq in
 
-1)
-r=3
-let "r--"
-echo "$(head -$r $acc)" >> temp
-let "r=r+2"
-echo -en "\nEnter Password : " 
-read pas
-echo "$pas" >> temp
-echo "$(tail +$r $acc)" >> temp
-;;
+		1)
+			r=3
+			let "r--"
+			echo "$(head -$r $acc)" >> temp
+			let "r=r+2"
+			echo -en "\nEnter Password : " 
+			read pas
+			echo "$pas" >> temp
+			echo "$(tail +$r $acc)" >> temp
+			echo -en "\n\nDetails Updated.\nEnter any key to continue "
+			read gap
+		;;
 
 
-2)
-r=5
-let "r--"
-echo "$(head -$r $acc)" >> temp
-let "r=r+2"
-echo -en "\nEnter Address : " 
-read ad
-echo "$ad" >> temp
-echo "$(tail +$r $acc)" >> temp
-;;
-3)
-r=6
-let "r--"
-echo "$(head -$r $acc)" >> temp
-let "r=r+2"
-echo -en "\nEnter DOB : " 
-read dob
-echo "$dob" >> temp
-echo "$(tail +$r $acc)" >> temp
-;;
-4)
-r=7
-let "r--"
-echo "$(head -$r $acc)" >> temp
-let "r=r+2"
-echo -en "\nEnter Aadhar : " 
-read adh
-echo "$adh" >> temp
-echo "$(tail +$r $acc)" >> temp
-;;
-5)
-r=8
-let "r--"
-echo "$(head -$r $acc)" >> temp
-let "r=r+2"
-echo -en "\nEnter Email : " 
-read email
-echo "$email" >> temp
-echo "$(tail +$r $acc)" >> temp
-;;
+		2)
+			r=5
+			let "r--"
+			echo "$(head -$r $acc)" >> temp
+			let "r=r+2"
+			echo -en "\nEnter Address : " 
+			read ad
+			echo "$ad" >> temp
+			echo "$(tail +$r $acc)" >> temp
+			echo -en "\n\nDetails Updated.\nEnter any key to continue "
+			read gap
+		;;
+		3)
+			r=6
+			let "r--"
+			echo "$(head -$r $acc)" >> temp
+			let "r=r+2"
+			echo -en "\nEnter DOB : " 
+			unset dob
+			k=1
+			while [[ ! $dob =~ ^(0[1-9]|[1-2][0-9]|3[0-1])[-/.](0[1-9]|1[0-2])[-/.][0-9]{4}$ ]];
+			do
+				if [ $k -gt 1 ] ;
+				then
+				echo -en "\nEnter Correct DOB : "
+				fi
+				read dob
+				let "k=k+1"
+			done
+			echo "$dob" >> temp
+			echo "$(tail +$r $acc)" >> temp
+			echo -en "\n\nDetails Updated.\nEnter any key to continue "
+			read gap
+		;;
+		4)
+			r=7
+			let "r--"
+			echo "$(head -$r $acc)" >> temp
+			let "r=r+2"
+			echo -en "\nEnter Aadhar : " 
+			unset adh
+			k=1
+			while [[ ! $adh =~ ^[0-9]{12}$ ]];
+			do
+				if [ $k -gt 1 ] ;
+				then
+				echo -en "\nEnter Correct Aadhaar No : "
+				fi
+				read adh
+				let "k=k+1"
+			done
+			echo "$adh" >> temp
+			echo "$(tail +$r $acc)" >> temp
+			echo -en "\n\nDetails Updated.\nEnter any key to continue "
+			read gap
+		;;
+		5)
+			r=8
+			let "r--"
+			echo "$(head -$r $acc)" >> temp
+			let "r=r+2"
+			echo -en "\nEnter Email : " 
+			read email
+			echo "$email" >> temp
+			echo "$(tail +$r $acc)" >> temp
+			echo -en "\n\nDetails Updated.\nEnter any key to continue "
+			read gap
+		;;
 
-6)
-r=9
-let "r--"
-echo "$(head -$r $acc)" >> temp
-let "r=r+2"
-echo -en "\nEnter Phone No : " 
-read ph
-echo "$ph" >> temp
-echo "$(tail +$r $acc)" >> temp
-;;
+		6)
+			r=9
+			let "r--"
+			echo "$(head -$r $acc)" >> temp
+			let "r=r+2"
+			echo -en "\nEnter Phone No : " 
+			unset ph
+			k=1
+			while [[ ! $ph =~ ^[1-9][0-9]{9}$ ]];
+			do
+				if [ $k -gt 1 ] ;
+				then
+				echo -en "\nEnter Correct Phone No : "
+				fi
+				read ph
+				let "k=k+1"
+			done
+			echo "$ph" >> temp
+			echo "$(tail +$r $acc)" >> temp
+			echo -en "\n\nDetails Updated.\nEnter any key to continue "
+			read gap
+		;;
 
-7)
-;;
+		7)
+			l=2
+		;;
 
-*)
-echo -en "\n\nInvalid Input";;
-esac
+		*)
+			echo -en "\n\nInvalid Input!!!\nEnter any key to continue ."
+			read gap
+		;;
 
-if [ -f "temp" ];
-then
-rm -r $acc
-mv temp $acc
-fi
+		esac
 
+		if [ -f "temp" ];
+		then
+			rm -r $acc
+			mv temp $acc
+		fi
+done
 else
-echo -e "\nOops!! Account Not Found"
-read gap
+	echo -e "\n\nOops!! Account Not Found.\nEnter any key to continue ."
+	read gap
 fi 
+
+
+
+
+
+
+
diff --git a/Project/admin b/Project/admin
--- a/Project/admin
+++ b/Project/admin
@@ -5,14 +5,27 @@ while [ $j -eq 1 ]
 do
 clear
 
-echo -e "\n\tWelcome to Admin Menu\n"
-echo -e "\n1. Add Accounts \n2. Edit Accounts \n3. Veiw Account \n4. View All Accounts \n5. Delete Account \n6. Forms \n7. Exit\n"
+echo -en "\n\t __          __  _                            _                      _           _         __  __                  "
+echo -en "\n\t \ \        / / | |                          | |            /\      | |         (_)       |  \/  |                 "
+echo -en "\n\t  \ \  /\  / /__| | ___ ___  _ __ ___   ___  | |_ ___      /  \   __| |_ __ ___  _ _ __   | \  / | ___ _ __  _   _ "
+echo -en "\n\t   \ \/  \/ / _ \ |/ __/ _ \|  _   _ \ / _ \ | __/ _ \    / /\ \ / _  |  _   _ \| |  _ \  | |\/| |/ _ \  _ \| | | |"
+echo -en "\n\t    \  /\  /  __/ | (_| (_) | | | | | |  __/ | || (_) |  / ____ \ (_| | | | | | | | | | | | |  | |  __/ | | | |_| |"
+echo -en "\n\t     \/  \/ \___|_|\___\___/|_| |_| |_|\___|  \__\___/  /_/    \_\__,_|_| |_| |_|_|_| |_| |_|  |_|\___|_| |_|\____|"
+
+echo -e "\n\n\n1. Add Accounts \n2. Edit Accounts \n3. Veiw Account \n4. View All Accounts \n5. Delete Account \n6. Forms \n7. Exit\n"
 echo -n "Enter Your Choice : "
 read choice 
 case $choice in
 
 	1)
-	echo -ne "\n\n\tAdd \n1. Saving Account \n2. Current Account\n\nEnter Your Choice : "
+	clear
+	echo -en "\n\t              _     _                                     _   "
+	echo -en "\n\t     /\      | |   | |     /\                            | |  "
+	echo -en "\n\t    /  \   __| | __| |    /  \   ___ ___ ___  _   _ _ __ | |_ "
+	echo -en "\n\t   / /\ \ / _  |/ _  |   / /\ \ / __/ __/ _ \| | | |  _ \| __|"
+	echo -en "\n\t  / ____ \ (_| | (_| |  / ____ \ (_| (_| (_) | |_| | | | | |_ "
+	echo -en "\n\t /_/    \_\____|\____| /_/    \_\___\___\___/ \____|_| |_|\__|"
+	echo -ne "\n\n\n1. Saving Account \n2. Current Account\n\nEnter Your Choice : "
 	read c
 
 		case $c in
@@ -25,7 +38,8 @@ case $choice in
 		;;
 
 		*)
-		echo "Sorry,Wrong Input";;
+		echo -e "\nOops!!! Wrong Input. \nPress Any Key To Continue "
+		read gap;;
 		esac
 	;;
 
@@ -33,7 +47,14 @@ case $choice in
 		./adedit ;;
 
 	3)
-		echo -en "\n\nEnter Account No : " 
+		clear
+		echo -en "\n\t __      ___                                                   _  " 
+		echo -en "\n\t \ \    / (_)                   /\                            | |  "
+		echo -en "\n\t  \ \  / / _  _____      __    /  \   ___ ___ ___  _   _ _ __ | |_ "
+		echo -en "\n\t   \ \/ / | |/ _ \ \ /\ / /   / /\ \ / __/ __/ _ \| | | | '_ \| __|"
+		echo -en "\n\t    \  /  | |  __/\ V  V /   / ____ \ (_| (_| (_) | |_| | | | | |_ "
+		echo -en "\n\t     \/   |_|\___| \_/\_/   /_/    \_\___\___\___/ \__,_|_| |_|\__|"
+		echo -en "\n\n\nEnter Account No : " 
 		read accc
 		cd ./accounts
 		./custview $accc
@@ -53,11 +74,18 @@ case $choice in
 	j=2;;
 
 	*)
-	echo -en "\nInvalid Input\t"
-	echo -e "\nPress Any Key To Continue "
+	echo -en "\nInvalid Input!!! \nPress Any Key To Continue "
 	read gap
 	 ;; 
 
 esac
 
 done
+
+
+
+
+
+
+
+
diff --git a/Project/custmenu b/Project/custmenu
--- a/Project/custmenu
+++ b/Project/custmenu
@@ -1,28 +1,43 @@
 #! /bin/bash
 
-clear
-echo -e "\n\tCustomer Menu\n\n1. Login Account \n2. Account Opening Form \n3. Exit\n"
-echo -n "Enter Your Choice : "
-read choice 
 
-case $choice in
+p=1
+while [ $p -eq 1 ]
+do
+	clear
+	echo -en "\n\t   _____          _                              __  __                  "
+	echo -en "\n\t  / ____|        | |                            |  \/  |                 "
+	echo -en "\n\t | |    _   _ ___| |_ ___  _ __ ___   ___ _ __  | \  / | ___ _ __  _   _ "
+	echo -en "\n\t | |   | | | / __| __/ _ \|  _   _ \ / _ \  __| | |\/| |/ _ \  _ \| | | |"
+	echo -en "\n\t | |___| |_| \__ \ || (_) | | | | | |  __/ |    | |  | |  __/ | | | |_| |"
+	echo -en "\n\t  \_____\__,_|___/\__\___/|_| |_| |_|\___|_|    |_|  |_|\___|_| |_|\__,_|"
+	echo -e "\n\n\n1. Login Account \n2. Account Opening Form \n3. Exit\n"
+	echo -n "Enter Your Choice : "
+	read choice 
 
-1)
-./log 
-;; 
+	case $choice in
 
-2)
-./form
-;;
+		1)
+			./log 
+			;; 
 
-3)
+		2)
+			./form
+			;;
 
-;;
+		3)
+			p=2
+			;;
 
-*)
-echo -en "Oops!! Invalid Input "
-echo -e "\nPress Any Key To Continue "
-read gap
-;;
+		*)
+			echo -en "\n\nOops!! Invalid Input "
+			echo -e "\nPress Any Key To Continue "
+			read gap
+		;;
 
-esac
+	esac
+
+done
+
+
+
